# Generated by Django 6.0.5 on 2026-05-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='naem',
            new_name='name',
        ),
    ]
